version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: jang_search_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/jang_search_system
    ports:
      - "8000:8000"
    depends_on:
      - db